base_url = "https://orbitofdeceit.github.io"
title = "The Paranoid Tip"
description = "Magnet for tweet bots, unwanted social media gurus and online marketing"
default_language = "en"
build_search_index = false

# Enable RSS feeds and sitemap
generate_feeds = true
feed_filenames = ["rss.xml"]
generate_sitemap = true

# Enable categories taxonomy with RSS feed
taxonomies = [
    {name = "categories", feed = true},
]

# Add author information
author = "Neil Thraves"

[extra]
github_username = "orbitofdeceit"
