name: Jekyll CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          # Use Ruby 2.7 to match older gem constraints (ruby_dep and github-pages' dependencies)
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Build site with Jekyll
        run: bundle exec jekyll build --destination _site

      - name: Upload built site
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: _site
